import { Dimensions, StyleSheet } from "react-native";
import { colors } from "@/src/constants/colors";

const { width } = Dimensions.get("window");
const CARD_WIDTH = width - 32;
const CARD_HEIGHT = 200;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  pageBody: {
    backgroundColor: colors.mainBackground,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    marginTop: -28,
    paddingTop: 20,
    zIndex: 2,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 50,
  },
  welcomeSection: {
    paddingHorizontal: 20,
    paddingVertical: 26,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 16,
    overflow: "hidden",
    flexDirection: "row",
  },
  decorationCircleLarge: {
    position: "absolute",
    right: -20,
    top: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  decorationCircleSmall: {
    position: "absolute",
    right: 16,
    bottom: 12,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  welcomeLeft: { flex: 1 },
  welcomeRight: {
    width: 130,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  welcomeKicker: {
    fontSize: 14,
    color: "#E3F2FD",
    opacity: 0.95,
    marginBottom: 8,
    fontWeight: "600",
  },
  weatherRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  weatherChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  weatherText: {
    marginLeft: 6,
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.primary,
    marginHorizontal: 6,
    opacity: 0.5,
  },
  miniCta: {
    marginLeft: 10,
    backgroundColor: "#005A90",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  miniCtaText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    marginRight: 6,
  },
  timeTextHero: { color: colors.white, fontSize: 26, fontWeight: "800" },
  dateTextHero: { color: "#EAF6FF", fontSize: 12, marginBottom: 4 },
  timeBackdrop: {
    position: "absolute",
    right: -6,
    top: -6,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  quickActionsSection: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickActionsGrid: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginTop: 0,
  },
  quickActionItem: {
    width: (width - 120) / 4,
    alignItems: "center",
  },
  quickActionTile: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  quickActionInner: {
    alignItems: "center",
    justifyContent: "center",
  },
  actionTitleBelow: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "600",
    color: colors.text,
    textAlign: "center",
  },
  coursesSection: {
    paddingVertical: 30,
    paddingBottom: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.titleColor,
  },
  seeAllText: {
    fontSize: 16,
    color: colors.titleColor,
    fontWeight: "500",
  },
  coursesContainer: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  courseCard: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT + 140,
    marginRight: 16,
    borderRadius: 16,
    backgroundColor: colors.mainBackground,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    overflow: "hidden",
  },
  courseImageContainer: {
    height: CARD_HEIGHT,
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
  },
  courseImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  priceTag: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  priceText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "bold",
  },
  courseContent: {
    padding: 16,
    flex: 1,
    justifyContent: "flex-start",
  },
  textContentSection: {
    marginBottom: 6,
  },
  courseTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 8,
    lineHeight: 24,
  },
  courseDescription: {
    fontSize: 14,
    color: colors.text,
    opacity: 0.8,
    lineHeight: 20,
    marginBottom: 6,
    minHeight: 40,
  },
  courseInfo: {
    flexDirection: "row",
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  infoText: {
    fontSize: 12,
    color: colors.text,
    marginLeft: 4,
    opacity: 0.8,
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: "center",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: colors.text,
    opacity: 0.7,
  },
  emptyContainer: {
    paddingVertical: 40,
    alignItems: "center",
  },
  emptyText: {
    marginTop: 12,
    fontSize: 16,
    color: colors.text,
    opacity: 0.7,
  },
  statsSection: {
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.white,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginHorizontal: 6,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.primary,
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    color: colors.text,
    opacity: 0.7,
    marginTop: 4,
  },
});
