import { colors } from "@/src/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  backButton: {
    marginRight: 12,
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.backgroundSecondary,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  headerIconContainer: {
    marginRight: 12,
  },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 3,
    fontWeight: "500",
  },
  keyboardView: {
    flex: 1,
  },
  messagesList: {
    padding: 20,
    paddingBottom: 24,
  },
  messageContainer: {
    marginBottom: 12,
    flexDirection: "row",
  },
  userMessageContainer: {
    justifyContent: "flex-end",
  },
  aiMessageContainer: {
    justifyContent: "flex-start",
  },
  messageBubble: {
    maxWidth: "82%",
    minWidth: 60,
    padding: 16,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  userBubble: {
    backgroundColor: colors.primary,
    borderBottomRightRadius: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  aiBubble: {
    backgroundColor: colors.background,
    borderBottomLeftRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  aiIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 2,
    flexShrink: 0,
  },
  messageText: {
    fontSize: 15.5,
    lineHeight: 23,
    flexShrink: 1,
    letterSpacing: 0.1,
  },
  userMessageText: {
    color: "#FFFFFF",
  },
  aiMessageText: {
    color: colors.text,
  },
  inputContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    paddingBottom: 16,
    // backgroundColor: colors.background,
    // borderTopWidth: 1,
    // borderTopColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 8,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    maxHeight: 100,
    paddingVertical: 8,
    marginRight: 10,
    lineHeight: 20,
    minHeight: 36,
  },
  sendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  sendButtonDisabled: {
    backgroundColor: colors.gray[300],
    opacity: 0.6,
    shadowOpacity: 0,
    elevation: 0,
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.backgroundSecondary,
    marginLeft: 4,
  },
  editContainer: {
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: 12,
  },
  editInput: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    minHeight: 44,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: colors.primary,
    marginBottom: 8,
  },
  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  editCancelButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  editSaveButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  messageMenu: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 8,
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 8,
    gap: 12,
  },
  menuItemText: {
    fontSize: 16,
    color: colors.text,
    fontWeight: "500",
  },
  hamburgerButton: {
    marginRight: 12,
    padding: 8,
    borderRadius: 20,
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 998,
  },
  drawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 300,
    backgroundColor: colors.background,
    zIndex: 999,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 16,
  },
  drawerHeader: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  drawerHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  drawerTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: colors.text,
  },
  drawerCloseButton: {
    padding: 4,
  },
  drawerSearchContainer: {
    marginBottom: 12,
  },
  drawerSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  drawerSearchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    padding: 0,
  },
  drawerNewChatButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  drawerNewChatIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  drawerNewChatText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
  },
  drawerContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  drawerEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  drawerEmptyText: {
    fontSize: 16,
    color: colors.gray[400],
    marginTop: 16,
  },
  drawerConversationItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: "transparent",
  },
  drawerConversationItemActive: {
    backgroundColor: "rgba(0, 62, 159, 0.08)",
    borderColor: colors.primary,
  },
  drawerConversationContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  drawerConversationIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 2,
  },
  drawerConversationTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
    flex: 1,
    lineHeight: 20,
  },
  drawerConversationPreview: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  deleteModalContainer: {
    backgroundColor: colors.background,
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 24,
    maxWidth: 400,
    alignSelf: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  deleteModalIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 12,
    textAlign: "center",
  },
  deleteModalMessage: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
  },
  deleteModalActions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  deleteModalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  deleteModalCancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  deleteModalConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#EF4444",
    alignItems: "center",
  },
  deleteModalConfirmText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  // --- Suggestion chip & preview modal ---
  suggestionContainer: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  suggestionChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(0, 62, 159, 0.08)",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  suggestionChipText: {
    color: colors.primary,
    fontSize: 13.5,
    fontWeight: "600",
  },
  previewContainer: {
    backgroundColor: colors.background,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    maxWidth: 480,
    width: "92%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 16,
  },
  previewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  previewIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  previewTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
  },
  previewErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(209, 67, 67, 0.08)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.error || "#D14343",
    padding: 10,
    marginTop: 12,
  },
  previewErrorText: {
    flex: 1,
    color: colors.error || "#D14343",
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  previewTitleEditButton: {
    padding: 4,
    marginLeft: 8,
  },
  previewTitleInputContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  previewTitleInput: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
    padding: 0,
  },
  previewTitleSaveButton: {
    padding: 4,
    marginLeft: 8,
  },
  previewScrollView: {
    maxHeight: 360,
  },
  previewStepContainer: {
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  previewStepDragging: {
    opacity: 0.7,
    // transform: [{ scale: 1.02 }],
    shadowColor: "#000",
    borderWidth: 1.2,
    borderColor: colors.primary,
  },
  previewStepContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
  },
  previewStepDragHandle: {
    marginRight: 8,
    padding: 4,
  },
  previewStepIndex: {
    width: 24,
    alignItems: "center",
    marginRight: 8,
  },
  previewStepIndexText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  previewStepInfo: {
    flex: 1,
    marginRight: 8,
  },
  previewStepTitle: {
    fontSize: 14.5,
    color: colors.text,
    fontWeight: "600",
    marginBottom: 4,
  },
  previewStepCourse: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  previewStepDelete: {
    padding: 4,
  },
  previewEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  previewEmptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginTop: 12,
  },
  previewEmptySubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  previewAddCourseButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: "rgba(0, 62, 159, 0.08)",
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: "dashed",
    marginTop: 8,
    marginBottom: 4,
  },
  previewAddCourseText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 8,
  },
  // Course Picker Modal Styles
  coursePickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  coursePickerContainer: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  coursePickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  coursePickerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
  },
  coursePickerCloseButton: {
    padding: 4,
  },
  coursePickerSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    margin: 16,
    marginBottom: 12,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  coursePickerSearchIcon: {
    marginRight: 8,
  },
  coursePickerSearchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    padding: 0,
  },
  coursePickerClearButton: {
    padding: 4,
    marginLeft: 8,
  },
  coursePickerLoading: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  coursePickerList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  coursePickerEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  coursePickerEmptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    marginTop: 16,
  },
  coursePickerItem: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  coursePickerItemAdded: {
    opacity: 0.6,
    backgroundColor: "rgba(0, 62, 159, 0.05)",
  },
  coursePickerItemContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coursePickerItemInfo: {
    flex: 1,
    marginRight: 12,
  },
  coursePickerItemTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 4,
  },
  coursePickerItemDescription: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 4,
    lineHeight: 20,
  },
  coursePickerItemPrice: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
    marginTop: 4,
  },
  coursePickerItemBadge: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  previewActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  previewCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  previewCancelText: {
    color: colors.text,
    fontWeight: "600",
  },
  previewConfirm: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  previewConfirmText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  // success modal
  successContainer: {
    backgroundColor: colors.background,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    maxWidth: 420,
    width: "90%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 16,
  },
  successHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  successIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  successTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
  },
  successSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  successStepsContainer: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    marginBottom: 14,
    maxHeight: 240,
  },
  successStepsScroll: {
    maxHeight: 240,
  },
  successStepsContent: {
    paddingVertical: 6,
  },
  successStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  successStepIndex: {
    width: 20,
    alignItems: "center",
    marginRight: 10,
  },
  successStepIndexText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  successStepInfo: {
    flex: 1,
  },
  successStepTitle: {
    fontSize: 14,
    color: colors.text,
    fontWeight: "600",
    marginBottom: 2,
  },
  successStepDescription: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  successActions: {
    flexDirection: "row",
    gap: 10,
  },
  successClose: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  successCloseText: {
    color: colors.text,
    fontWeight: "600",
  },
  successNavigate: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  successNavigateText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});
