import { colors } from "@/src/constants/colors";
import { StyleSheet } from "react-native";

// Chat-specific colors (green/teal theme)
const chatColors = {
  primary: "#10B981", // Vibrant green for send button
  primaryDark: "#047857", // Darker green
  primaryLight: "#34D399", // Light green
  lightGreen: "#D1FAE5", // Light green for buttons/cards
  gradientStart: "#10B981", // Vibrant green start (top-left)
  gradientEnd: "#0F172A", // Dark blue/black end (bottom-right)
  aiBubbleBg: "#374151", // Dark gray for AI messages
  aiBubbleText: "#FFFFFF",
  inputBg: "#1F2937", // Dark gray for input
  inputText: "#FFFFFF",
  inputPlaceholder: "#9CA3AF",
};

const drawerColors = {
  background: "#0B162C",
  headerBg: "#101F38",
  surface: "#142642",
  card: "#192E4D",
  cardActive: "#1F365C",
  border: "rgba(255, 255, 255, 0.08)",
  textPrimary: "#F5F7FB",
  textSecondary: "rgba(245, 247, 251, 0.78)",
};

export const styles = StyleSheet.create({
  screenBackground: {
    flex: 1,
    backgroundColor: colors.mainBackground,
    position: "relative",
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(4, 16, 37, 0.73)",
    zIndex: 1,
  },
  container: {
    flex: 1,
    position: "relative",
    backgroundColor: "transparent",
    zIndex: 2,
  },
  contentContainer: {
    flex: 1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -25,
    paddingTop: 20,
    overflow: "hidden",
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 6,
    zIndex: 1,
  },
  contentContainerEmpty: {
    marginTop: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
    backgroundColor: "transparent",
    shadowOpacity: 0,
    elevation: 0,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "transparent",
    borderBottomWidth: 0,
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    zIndex: 2,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flex: 1,
  },
  headerIconContainer: {
    padding: 8,
  },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  headerTextContainer: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.8)",
    marginTop: 3,
    fontWeight: "500",
  },
  keyboardView: {
    flex: 1,
  },
  messagesList: {
    padding: 20,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  messagesListNonEmpty: {
    paddingBottom: 140,
  },
  messagesListEmpty: {
    flex: 1,
    padding: 0,
    paddingBottom: 0,
  },
  listFooterContainer: {
    paddingTop: 12,
  },
  messageContainer: {
    marginBottom: 12,
    flexDirection: "row",
  },
  userMessageContainer: {
    justifyContent: "flex-end",
  },
  aiMessageContainer: {
    flexDirection: "column",
    alignItems: "flex-start",
    width: "100%",
  },
  messageBubble: {
    maxWidth: "82%",
    minWidth: 60,
    paddingVertical: 12,
    paddingLeft: 16,
    paddingRight: 14,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  userBubble: {
    backgroundColor: colors.primary,
    borderBottomRightRadius: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  aiBubble: {
    backgroundColor: "transparent",
    borderBottomLeftRadius: 0,
    borderRadius: 0,
    padding: 0,
    maxWidth: "100%",
    width: "100%",
    flex: 1,
    alignSelf: "stretch",
    shadowOpacity: 0,
    elevation: 0,
  },
  messageText: {
    fontSize: 15.5,
    lineHeight: 23,
    flexShrink: 1,
    letterSpacing: 0.1,
  },
  userMessageText: {
    color: "#FFFFFF",
  },
  aiMessageText: {
    color: chatColors.aiBubbleText,
  },
  markdownTextWrapper: {
    flexDirection: "column",
    width: "100%",
  },
  markdownHeading1: {
    fontSize: 20,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 6,
  },
  markdownHeading2: {
    fontSize: 18,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 6,
  },
  markdownHeading3: {
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 4,
  },
  markdownParagraph: {
    marginBottom: 4,
  },
  markdownListItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  markdownListBullet: {
    marginRight: 8,
    lineHeight: 22,
  },
  markdownListText: {
    flex: 1,
    marginBottom: 0,
  },
  markdownSpacer: {
    height: 10,
  },
  analysisTextFaded: {
    opacity: 0.4,
  },
  inputContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "transparent",
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inputField: {
    flex: 1,
    backgroundColor: chatColors.inputBg,
    borderRadius: 24,
    paddingLeft: 16,
    paddingRight: 12,
    paddingVertical: 10,
    minHeight: 48,
    maxHeight: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: chatColors.inputText,
    paddingVertical: 0,
    lineHeight: 20,
    minHeight: 24,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  sendButtonDisabled: {
    backgroundColor: colors.gray[300],
    opacity: 0.6,
    shadowOpacity: 0,
    elevation: 0,
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.backgroundSecondary,
    marginLeft: 4,
  },
  editContainer: {
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: 12,
  },
  editInput: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    minHeight: 44,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: colors.primary,
    marginBottom: 8,
  },
  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  editCancelButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  editSaveButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  messageMenu: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 8,
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 8,
    gap: 12,
  },
  menuItemText: {
    fontSize: 16,
    color: colors.text,
    fontWeight: "500",
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    // backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 998,
  },
  drawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 300,
    backgroundColor: drawerColors.background,
    zIndex: 999,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 16,
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    overflow: "hidden",
  },
  drawerHeader: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: drawerColors.border,
    backgroundColor: drawerColors.headerBg,
  },
  drawerHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  drawerTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: drawerColors.textPrimary,
  },
  drawerCloseButton: {
    padding: 4,
  },
  drawerSearchContainer: {
    marginBottom: 12,
  },
  drawerSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: drawerColors.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: drawerColors.border,
  },
  drawerSearchInput: {
    flex: 1,
    fontSize: 15,
    color: drawerColors.textPrimary,
    padding: 0,
  },
  drawerNewChatButton: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: colors.white,
    borderRadius: 12,
    padding: 12,
  },
  drawerNewChatIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  drawerNewChatText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.white,
  },
  drawerContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: drawerColors.surface,
  },
  drawerEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  drawerEmptyText: {
    fontSize: 16,
    color: drawerColors.textSecondary,
    marginTop: 16,
  },
  drawerConversationItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: drawerColors.card,
    borderWidth: 1,
    borderColor: drawerColors.border,
  },
  drawerConversationItemActive: {
    backgroundColor: drawerColors.cardActive,
    borderColor: colors.primary,
  },
  drawerConversationContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  drawerConversationIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: drawerColors.cardActive,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 2,
  },
  drawerConversationTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: drawerColors.textPrimary,
    flex: 1,
    lineHeight: 20,
  },
  drawerConversationPreview: {
    fontSize: 13,
    color: drawerColors.textSecondary,
    lineHeight: 18,
  },
  deleteModalContainer: {
    backgroundColor: colors.background,
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 24,
    maxWidth: 400,
    alignSelf: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  deleteModalIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 12,
    textAlign: "center",
  },
  deleteModalMessage: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
  },
  deleteModalActions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  deleteModalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  deleteModalCancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  deleteModalConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#EF4444",
    alignItems: "center",
  },
  deleteModalConfirmText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  // --- Suggestion chip & preview modal ---
  suggestionContainer: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  suggestionChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.white,
    borderWidth: 0,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  suggestionChipText: {
    color: colors.primary,
    fontSize: 13.5,
    fontWeight: "600",
  },
  previewContainer: {
    backgroundColor: colors.background,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    maxWidth: 480,
    width: "92%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 16,
  },
  previewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  previewIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  previewTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
  },
  previewErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(209, 67, 67, 0.08)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.error || "#D14343",
    padding: 10,
    marginTop: 12,
  },
  previewErrorText: {
    flex: 1,
    color: colors.error || "#D14343",
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  previewTitleEditButton: {
    padding: 4,
    marginLeft: 8,
  },
  previewTitleInputContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  previewTitleInput: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
    padding: 0,
  },
  previewTitleSaveButton: {
    padding: 4,
    marginLeft: 8,
  },
  previewScrollView: {
    maxHeight: 360,
  },
  previewStepContainer: {
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  previewStepDragging: {
    opacity: 0.7,
    // transform: [{ scale: 1.02 }],
    shadowColor: "#000",
    borderWidth: 1.2,
    borderColor: colors.primary,
  },
  previewStepContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
  },
  previewStepDragHandle: {
    marginRight: 8,
    padding: 4,
  },
  previewStepIndex: {
    width: 24,
    alignItems: "center",
    marginRight: 8,
  },
  previewStepIndexText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  previewStepInfo: {
    flex: 1,
    marginRight: 8,
  },
  previewStepTitle: {
    fontSize: 14.5,
    color: colors.text,
    fontWeight: "600",
    marginBottom: 4,
  },
  previewStepCourse: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  previewStepDelete: {
    padding: 4,
  },
  previewEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  previewEmptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginTop: 12,
  },
  previewEmptySubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  previewAddCourseButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: "rgba(0, 62, 159, 0.08)",
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: "dashed",
    marginTop: 8,
    marginBottom: 4,
  },
  previewAddCourseText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 8,
  },
  // Course Picker Modal Styles
  coursePickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  coursePickerContainer: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  coursePickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  coursePickerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
  },
  coursePickerCloseButton: {
    padding: 4,
  },
  coursePickerSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    margin: 16,
    marginBottom: 12,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  coursePickerSearchIcon: {
    marginRight: 8,
  },
  coursePickerSearchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    padding: 0,
  },
  coursePickerClearButton: {
    padding: 4,
    marginLeft: 8,
  },
  coursePickerLoading: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  coursePickerList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  coursePickerEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  coursePickerEmptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    marginTop: 16,
  },
  coursePickerItem: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  coursePickerItemAdded: {
    opacity: 0.6,
    backgroundColor: "rgba(0, 62, 159, 0.05)",
  },
  coursePickerItemContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coursePickerItemInfo: {
    flex: 1,
    marginRight: 12,
  },
  coursePickerItemTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 4,
  },
  coursePickerItemDescription: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 4,
    lineHeight: 20,
  },
  coursePickerItemPrice: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
    marginTop: 4,
  },
  coursePickerItemBadge: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  previewActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  previewCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  previewCancelText: {
    color: colors.text,
    fontWeight: "600",
  },
  previewConfirm: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  previewConfirmText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  // success modal
  successContainer: {
    backgroundColor: colors.background,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    maxWidth: 420,
    width: "90%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 16,
  },
  successHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  successIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  successTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
  },
  successSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  successStepsContainer: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    marginBottom: 14,
    maxHeight: 240,
  },
  successStepsScroll: {
    maxHeight: 240,
  },
  successStepsContent: {
    paddingVertical: 6,
  },
  successStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  successStepIndex: {
    width: 20,
    alignItems: "center",
    marginRight: 10,
  },
  successStepIndexText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  successStepInfo: {
    flex: 1,
  },
  successStepTitle: {
    fontSize: 14,
    color: colors.text,
    fontWeight: "600",
    marginBottom: 2,
  },
  successStepDescription: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  successActions: {
    flexDirection: "row",
    gap: 10,
  },
  successClose: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  successCloseText: {
    color: colors.text,
    fontWeight: "600",
  },
  successNavigate: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  successNavigateText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  // Empty State Styles
  emptyStateContainer: {
    flex: 1,
    width: "100%",
    backgroundColor: "rgba(4, 16, 37, 0.3)",
  },
  emptyStateScrollView: {
    flex: 1,
  },
  emptyStateScrollContent: {
    flexGrow: 1,
    paddingBottom: 0,
  },
  gradientContainer: {
    width: "100%",
    marginBottom: 0,
    paddingBottom: 0,
    backgroundColor: "transparent",
  },
  greetingSection: {
    width: "100%",
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 60,
    position: "relative",
    overflow: "hidden",
  },
  emptyStateMenuButton: {
    position: "absolute",
    left: 20,
    top: 16,
    zIndex: 10,
  },
  emptyStateMenuIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  // Greeting Styles
  greetingContainer: {
    paddingHorizontal: 0,
    marginBottom: 0,
    alignItems: "center",
  },
  greetingTitle: {
    fontSize: 32,
    fontWeight: "400",
    color: colors.white,
    marginBottom: 8,
    letterSpacing: 0.15,
    textAlign: "center",
  },
  greetingSubtitle: {
    fontSize: 30,
    fontWeight: "400",
    color: colors.white,
    marginBottom: 6,
    letterSpacing: 0.15,
    textAlign: "center",
  },
  greetingDescription: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.75)",
    marginTop: 2,
    lineHeight: 20,
    letterSpacing: 0.2,
    textAlign: "center",
  },
  quickActionsSection: {
    width: "100%",
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 0,
    marginBottom: 0,
  },
  // Quick Actions Styles
  quickActionsContainer: {
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
  quickActionsRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    width: "100%",
  },
  quickActionsRowCentered: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  quickActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(55, 65, 81, 0.75)",
    borderRadius: 16,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    paddingHorizontal: 14,
  },
  quickActionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.white,
    textAlign: "center",
  },
  // Popular Topics Styles
  popularTopicsSection: {
    position: "absolute",
    bottom: 70,
    left: 0,
    right: 0,
    width: "100%",
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 0,
    marginTop: 0,
  },
  popularTopicsContainer: {
    paddingHorizontal: 0,
    marginBottom: 0,
    paddingBottom: 0,
  },
  popularTopicsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  popularTopicsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.white,
  },
  popularTopicsSeeAll: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "500",
  },
  popularTopicsCards: {
    flexDirection: "row",
    marginBottom: 0,
  },
  popularTopicCard: {
    flex: 1,
    backgroundColor: "rgba(75, 85, 99, 0.4)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    minHeight: 120,
    marginRight: 12,
  },
  popularTopicCardLast: {
    marginRight: 0,
  },
  popularTopicIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  popularTopicText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.white,
    lineHeight: 22,
  },
  messageActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 12,
    alignSelf: "flex-start",
  },
  messageActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  messageActionText: {
    display: "none",
  },
  // Quick reply suggestions
  quickReplyContainer: {
    marginTop: 12,
    marginBottom: 8,
  },
  quickReplyHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  quickReplyTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: chatColors.aiBubbleText,
    marginRight: 8,
  },
  quickReplyArrow: {
    width: 16,
    height: 16,
  },
  quickReplySuggestions: {
    flexDirection: "column",
    gap: 8,
  },
  quickReplyItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  quickReplyIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  quickReplyText: {
    fontSize: 14,
    color: chatColors.aiBubbleText,
    fontWeight: "500",
    flex: 1,
  },
  quickReplyShareButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
  quickReplyShareText: {
    fontSize: 13,
    color: chatColors.aiBubbleText,
    fontWeight: "600",
  },
  microphoneButton: {
    width: 28,
    height: 32,
    borderRadius: 16,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
});

// Export chat colors for use in component
export { chatColors };
