export const strings = {
  // Common
  common: {
    loading: "Đang tải...",
    error: "Có lỗi xảy ra",
    success: "Thành công",
    cancel: "Hủy",
    confirm: "Xác nhận",
    save: "Lưu",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    back: "Quay lại",
    next: "Tiếp theo",
    previous: "Trước",
    done: "Hoàn thành",
    retry: "Thử lại",
    refresh: "Làm mới",
    search: "Tìm kiếm",
    filter: "Lọc",
    sort: "Sắp xếp",
    close: "Đóng",
    open: "Mở",
    yes: "Có",
    no: "Không",
    ok: "OK",
  },

  // Authentication
  auth: {
    login: "Đăng nhập",
    logout: "Đăng xuất",
    register: "Đăng ký",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    rememberMe: "Ghi nhớ đăng nhập",
    loginSuccess: "Đăng nhập thành công",
    loginError: "Đăng nhập thất bại",
    logoutSuccess: "Đăng xuất thành công",
    invalidCredentials: "Email hoặc mật khẩu không đúng",
  },

  // Navigation
  navigation: {
    home: "Trang chủ",
    courses: "Khóa học",
    schedule: "Lịch học",
    chat: "Tin nhắn",
    profile: "Hồ sơ",
    settings: "Cài đặt",
    notifications: "Thông báo",
    explore: "Khám phá",
    qrCode: "Mã QR",
  },

  // Courses
  courses: {
    title: "Khóa học",
    myCourses: "Khóa học của tôi",
    availableCourses: "Khóa học có sẵn",
    courseDetail: "Chi tiết khóa học",
    enroll: "Đăng ký",
    enrolled: "Đã đăng ký",
    level: "Trình độ",
    duration: "Thời lượng",
    instructor: "Giảng viên",
    schedule: "Lịch học",
    price: "Giá",
    description: "Mô tả",
    requirements: "Yêu cầu",
    curriculum: "Chương trình học",
    reviews: "Đánh giá",
    rating: "Đánh giá",
    students: "Học viên",
    maxStudents: "Số học viên tối đa",
    category: "Danh mục",
    status: "Trạng thái",
    active: "Hoạt động",
    inactive: "Không hoạt động",
    full: "Đã đầy",
  },

  // Schedule
  schedule: {
    title: "Lịch học",
    today: "Hôm nay",
    tomorrow: "Ngày mai",
    thisWeek: "Tuần này",
    nextWeek: "Tuần sau",
    upcoming: "Sắp tới",
    past: "Đã qua",
    time: "Thời gian",
    location: "Địa điểm",
    instructor: "Giảng viên",
    course: "Khóa học",
    status: "Trạng thái",
    attended: "Có mặt",
    absent: "Vắng mặt",
    late: "Muộn",
  },

  // Chat
  chat: {
    title: "Tin nhắn",
    conversations: "Cuộc trò chuyện",
    newMessage: "Tin nhắn mới",
    typeMessage: "Nhập tin nhắn...",
    send: "Gửi",
    online: "Trực tuyến",
    offline: "Ngoại tuyến",
    lastSeen: "Hoạt động lần cuối",
    typing: "Đang nhập...",
    messageSent: "Tin nhắn đã gửi",
    messageDelivered: "Tin nhắn đã gửi",
    messageRead: "Tin nhắn đã đọc",
    noMessages: "Chưa có tin nhắn nào",
    noConversations: "Chưa có cuộc trò chuyện nào",
  },

  // Profile
  profile: {
    title: "Hồ sơ",
    personalInfo: "Thông tin cá nhân",
    editProfile: "Chỉnh sửa hồ sơ",
    changePassword: "Đổi mật khẩu",
    settings: "Cài đặt",
    help: "Trợ giúp",
    about: "Giới thiệu",
    version: "Phiên bản",
    logout: "Đăng xuất",
    name: "Họ tên",
    email: "Email",
    phone: "Số điện thoại",
    address: "Địa chỉ",
    birthday: "Ngày sinh",
    gender: "Giới tính",
    avatar: "Ảnh đại diện",
    male: "Nam",
    female: "Nữ",
    other: "Khác",
  },

  // Notifications
  notifications: {
    title: "Thông báo",
    all: "Tất cả",
    unread: "Chưa đọc",
    markAsRead: "Đánh dấu đã đọc",
    markAllAsRead: "Đánh dấu tất cả đã đọc",
    noNotifications: "Không có thông báo nào",
    newNotification: "Thông báo mới",
  },

  // Errors
  errors: {
    networkError: "Lỗi kết nối mạng",
    serverError: "Lỗi máy chủ",
    unauthorized: "Không có quyền truy cập",
    forbidden: "Bị cấm truy cập",
    notFound: "Không tìm thấy",
    validationError: "Lỗi xác thực",
    unknownError: "Lỗi không xác định",
    tryAgain: "Vui lòng thử lại",
  },

  // Success messages
  success: {
    saved: "Đã lưu thành công",
    updated: "Đã cập nhật thành công",
    deleted: "Đã xóa thành công",
    created: "Đã tạo thành công",
    sent: "Đã gửi thành công",
    enrolled: "Đã đăng ký thành công",
    unenrolled: "Đã hủy đăng ký thành công",
  },
};
