platform :ios, '13.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'

config = use_native_modules!

flipper_config = FlipperConfiguration.enabled

use_react_native!(
  :path => config[:reactNativePath],
  :hermes_enabled => true,
  :fabric_enabled => true,
  :app_path => "#{Pod::Config.instance.installation_root}/..",
  :flipper_configuration => flipper_config,
)

target 'pool-center' do

end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )
end