import { StyleSheet } from "react-native";
import { colors } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.primary,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  menuButton: {
    marginRight: 16,
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.white,
    letterSpacing: 0.5,
  },
  backButton: {
    padding: 4,
  },
  detailContainer: {
    flex: 1,
  },
  detailHeader: {
    backgroundColor: colors.primary,
    padding: 16,
    paddingBottom: 18,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  detailHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  detailTimeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  detailTimeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "600",
    marginLeft: 6,
  },
  detailHeaderText: {
    flex: 1,
  },
  noteButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  detailHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.white,
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  detailHeaderSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.95)",
    fontWeight: "500",
  },
  detailHeaderDateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 0,
  },
  detailCloseButton: {
    alignSelf: "center",
    height: 20,
    marginRight: 32,
  },
  detailTimeBadgeIcon: {
    marginRight: 6,
  },
  detailHeaderRightBtn: {
    marginLeft: 8,
    padding: 6,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  detailContent: {
    padding: 16,
    paddingTop: 18,
  },
  detailCard: {
    backgroundColor: colors.mainBackground,
    marginBottom: 16,
  },
  detailCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 12,
  },
  detailCardDivider: {
    height: 2,
    backgroundColor: colors.primary,
    marginBottom: 12,
    borderRadius: 1,
  },
  detailCardIconWrapper: {
    marginRight: 12,
  },
  detailCardIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 62, 159, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailCardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.2,
  },
  detailCardContent: {
    paddingTop: 4,
  },
  detailInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  detailInfoLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    marginRight: 12,
  },
  detailInfoLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.gray[600],
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  detailInfoValue: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    lineHeight: 18,
    letterSpacing: -0.1,
    flexShrink: 1,
    textAlign: "right",
  },
  detailInfoValueContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  detailInfoValueBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  detailInfoValueNumber: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: -0.2,
  },
  detailInfoValueUnit: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.gray[600],
  },
  detailInfoBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0, 62, 159, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 62, 159, 0.2)",
  },
  detailInfoBadgeType: {
    backgroundColor: colors.primary,
    borderColor: colors.primaryDark,
  },
  detailInfoBadgeMaintenance: {
    backgroundColor: "#FF6B35",
    borderColor: "#FF4500",
  },
  detailAttendanceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  detailAttendanceText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: 0.2,
  },
  // Styles cho phần khóa học sắp tới
  scrollContainer: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  upcomingCoursesSection: {
    backgroundColor: colors.white,
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 16,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    borderRadius: 16,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary,
  },
  courseCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  courseHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  courseIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  courseInfo: {
    flex: 1,
  },
  courseName: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 4,
  },
  attendanceBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  courseInstructor: {
    fontSize: 14,
    color: colors.grayc,
  },
  courseDate: {
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  courseDateText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.primary,
  },
  courseDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  courseDetailItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  courseDetailText: {
    fontSize: 12,
    color: colors.grayc,
    fontWeight: "500",
  },
  loadingContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  loadingText: {
    fontSize: 14,
    color: colors.grayc,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 32,
  },
  emptyStateText: {
    fontSize: 16,
    color: colors.grayc,
    marginTop: 12,
    textAlign: "center",
  },
});
