import { colors } from "@/src/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  classInfoCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  classInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  classInfoText: {
    marginLeft: 12,
    flex: 1,
  },
  className: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 4,
  },
  courseTitle: {
    fontSize: 14,
    color: colors.gray[500],
  },
  createNoteCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 12,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginTop: 12,
    padding: 12,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
    minHeight: 80,
    marginBottom: 12,
  },
  createButton: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 8,
  },
  createButtonDisabled: {
    backgroundColor: colors.gray[500],
  },
  mediaSection: {
    marginVertical: 12,
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  uploadButtonDisabled: {
    opacity: 0.6,
  },
  uploadButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 8,
  },
  mediaCount: {
    fontSize: 12,
    color: colors.gray[500],
    textAlign: "center",
    marginTop: 4,
  },
  mediaPreviewContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.gray[200],
  },
  mediaPreviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  mediaPreviewTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  // Modern session tabs
  sessionTabs: {
    marginBottom: 12,
  },
  sessionTabsContent: {
    paddingRight: 8,
  },
  sessionTab: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 18,
    marginRight: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray[200],
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
  },
  sessionTabActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  sessionTabIcon: {
    marginRight: 6,
  },
  sessionTabText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.primary,
    maxWidth: 140,
  },
  sessionTabTextActive: {
    color: colors.white,
  },
  sessionTabBadge: {
    marginLeft: 6,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.gray[100],
    alignItems: "center",
    justifyContent: "center",
  },
  sessionTabBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  sessionTabBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.primary,
  },
  sessionTabBadgeTextActive: {
    color: colors.white,
  },
  mediaCountBadge: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 24,
    alignItems: "center",
  },
  mediaCountText: {
    fontSize: 12,
    color: colors.white,
    fontWeight: "600",
  },
  mediaPreviewScroll: {
    maxHeight: 100,
  },
  mediaPreviewContent: {
    paddingRight: 16,
  },
  mediaPreviewItem: {
    marginRight: 12,
  },
  mediaPreviewCard: {
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  mediaPreviewImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
  },
  mediaPreviewVideo: {
    width: 80,
    height: 80,
    backgroundColor: colors.gray[800],
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  mediaPreviewOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    padding: 4,
  },
  mediaRemoveButton: {
    backgroundColor: colors.error,
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  studentSection: {
    marginVertical: 12,
  },
  studentLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
    marginBottom: 8,
  },
  createButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  notesSection: {
    marginBottom: 20,
  },
  loadingContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  loadingText: {
    color: colors.gray[500],
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.gray[500],
    marginTop: 12,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.gray[500],
    marginTop: 4,
    textAlign: "center",
  },
  noteCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  noteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  noteHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  noteAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray[100],
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  noteAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  noteMemberInfo: {
    flex: 1,
  },
  noteMemberName: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 2,
  },
  noteDate: {
    fontSize: 12,
    color: colors.gray[500],
  },
  noteContent: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    marginBottom: 8,
  },
  noteScheduleInfo: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.gray[200],
  },
  noteScheduleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  noteScheduleText: {
    fontSize: 12,
    color: colors.gray[600],
    marginLeft: 6,
  },
  noteUpdated: {
    fontSize: 12,
    color: colors.gray[500],
    marginTop: 8,
    fontStyle: "italic",
  },
  noteMediaContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.gray[200],
  },
  noteMediaTitle: {
    fontSize: 12,
    color: colors.gray[600],
    marginBottom: 8,
    fontWeight: "500",
  },
  noteMediaScroll: {
    maxHeight: 60,
  },
  noteMediaItem: {
    marginRight: 8,
  },
  noteMediaPlaceholder: {
    width: 50,
    height: 50,
    backgroundColor: colors.gray[100],
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  // FAB styles
  fab: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalHeaderSpacer: {
    width: 40,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.white,
    flex: 1,
    textAlign: "center",
    marginHorizontal: 40,
  },
  modalCloseButton: {
    position: "absolute",
    left: 20,
    top: 16,
    padding: 4,
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  noteActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noteActionButton: {
    padding: 8,
    borderRadius: 6,
    backgroundColor: colors.gray[100],
  },
  // Delete Modal styles
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  deleteModalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  deleteModalHeader: {
    alignItems: "center",
    marginBottom: 24,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.text,
    marginTop: 16,
    marginBottom: 8,
  },
  deleteModalMessage: {
    fontSize: 14,
    color: colors.gray[600],
    textAlign: "center",
    lineHeight: 20,
  },
  deleteModalActions: {
    flexDirection: "row",
    gap: 12,
  },
  deleteModalCancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray[300],
    backgroundColor: colors.white,
    alignItems: "center",
  },
  deleteModalCancelText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.gray[700],
  },
  deleteModalConfirmButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: colors.error,
    alignItems: "center",
  },
  deleteModalConfirmButtonDisabled: {
    backgroundColor: colors.gray[400],
  },
  deleteModalConfirmText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
  },
  // Media styles - Modern & Compact
  mediaGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    flexWrap: "wrap",
  },
  mediaThumbnail: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: colors.gray[200],
    borderWidth: 2,
    borderColor: colors.primary, // Debug border to see if image is there
  },
  mediaHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  mediaTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  mediaItem: {
    position: "relative",
    marginRight: 8,
    marginBottom: 8,
  },
  removeMediaButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 2,
  },
  moreMediaIndicator: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: colors.gray[100],
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderStyle: "dashed",
  },
  moreMediaText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.gray[600],
  },
  // Session header card
  sessionHeaderCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.gray[200],
    marginBottom: 8,
  },
  sessionHeaderTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  sessionHeaderSub: {
    marginTop: 2,
    fontSize: 13,
    color: colors.gray[600],
  },
  mediaThumbnailContainer: {
    borderRadius: 8,
    overflow: "hidden",
  },
  mediaDebugContainer: {
    position: "relative",
    width: 50,
    height: 50,
  },
  mediaDebugText: {
    position: "absolute",
    top: 2,
    right: 2,
    fontSize: 8,
    color: colors.white,
    backgroundColor: colors.primary,
    paddingHorizontal: 2,
    paddingVertical: 1,
    borderRadius: 2,
    fontWeight: "bold",
  },
  mediaFallback: {
    width: 50,
    height: 50,
    backgroundColor: colors.gray[100],
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
  },
  mediaFallbackText: {
    fontSize: 8,
    color: colors.gray[600],
    textAlign: "center",
  },
  // Image Preview styles
  imagePreviewOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  imagePreviewContainer: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
  },
  imagePreviewHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 20,
    zIndex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  imagePreviewCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  imagePreviewCounter: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
  },
  imagePreviewHeaderSpacer: {
    width: 40,
  },
  imagePreviewScroll: {
    flex: 1,
  },
  imagePreviewItem: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  imagePreviewImage: {
    width: "100%",
    height: "100%",
    maxHeight: 600,
    backgroundColor: colors.white,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  imagePreviewTitle: {
    position: "absolute",
    bottom: 60,
    left: 20,
    right: 20,
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
    textAlign: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  // Evaluation styles
  evaluationSection: {
    marginTop: 24,
    marginBottom: 24,
    padding: 24,
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.gray[200],
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  evaluationHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.gray[100],
  },
  evaluationTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.text,
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  evaluationSubtitle: {
    fontSize: 15,
    color: colors.textSecondary,
    marginBottom: 24,
    lineHeight: 22,
    fontWeight: "500",
  },
  criterionItem: {
    marginBottom: 20,
    padding: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
  },
  criterionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  criterionLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    flex: 1,
    letterSpacing: 0.3,
  },
  scoreIndicator: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  scoreIndicatorText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.white,
  },
  scoreContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  scoreButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 0,
    backgroundColor: colors.gray[50],
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  scoreButtonSelected: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  scoreText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
  },
  scoreTextSelected: {
    color: colors.white,
  },
  scoreLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  scoreLabelText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  // Evaluation Modal Styles
  evaluationNoteSection: {
    backgroundColor: colors.background,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  evaluationNoteLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 8,
  },
  evaluationNoteText: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 24,
  },
  evaluationResultsSection: {
    marginBottom: 20,
  },
  evaluationResultItem: {
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  evaluationResultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  evaluationResultTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    flex: 1,
  },
  evaluationScoreBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  evaluationScoreText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.white,
  },
  scoreVisualization: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  scoreStar: {
    marginRight: 4,
  },
  scoreDescription: {
    fontSize: 14,
    color: colors.textSecondary,
    fontStyle: "italic",
  },
  overallScoreSection: {
    marginTop: 16,
    padding: 0,
    backgroundColor: "transparent",
  },
  overallScoreLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 8,
  },
  overallScoreContainer: {
    alignItems: "center",
    padding: 16,
    backgroundColor: colors.primary,
    borderRadius: 16,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  overallScoreValue: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.white,
  },
  overallScoreFieldContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    padding: 16,
    backgroundColor: colors.primary,
    borderRadius: 12,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  overallScoreFieldLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.white,
    letterSpacing: 0.3,
    flex: 1,
  },
  overallScoreValueContainer: {
    alignItems: "flex-end",
  },
  overallScoreMax: {
    fontSize: 12,
    color: colors.white,
    opacity: 0.8,
    marginTop: 2,
  },
  // Modern styles for form_judge fields
  fieldContainer: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray[200],
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  booleanContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  booleanButton: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: colors.gray[50],
    borderRadius: 28,
    borderWidth: 0,
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  booleanButtonSelected: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  booleanButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.gray[600],
    letterSpacing: 0.5,
  },
  booleanButtonTextSelected: {
    color: colors.white,
  },
  textInputContainer: {
    marginTop: 8,
  },
  textInput: {
    borderWidth: 0,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.text,
    backgroundColor: colors.gray[50],
    fontWeight: "500",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  relationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 0,
    backgroundColor: "transparent",
  },
  relationText: {
    fontSize: 15,
    color: colors.text,
    fontWeight: "500",
  },
  relationButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.primary,
    borderRadius: 24,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  relationButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.white,
    letterSpacing: 0.5,
  },
  noFieldsContainer: {
    padding: 24,
    alignItems: "center",
    backgroundColor: colors.gray[50],
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray[200],
    borderStyle: "dashed",
  },
  noFieldsText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontStyle: "italic",
    fontWeight: "500",
  },
  // Modern styles for evaluation modal results
  fieldResultContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    padding: 16,
    backgroundColor: colors.gray[50],
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  fieldResultLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
    letterSpacing: 0.3,
    flex: 1,
  },
  booleanResultContainer: {
    alignItems: "center",
  },
  booleanResultText: {
    fontSize: 15,
    fontWeight: "600",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    letterSpacing: 0.5,
  },
  booleanResultSelected: {
    color: colors.white,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  booleanResultUnselected: {
    color: colors.gray[600],
    backgroundColor: colors.gray[100],
  },
  textResultContainer: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: colors.primary,
    borderRadius: 16,
  },
  textResultValue: {
    fontSize: 14,
    color: colors.white,
    fontWeight: "600",
    textAlign: "center",
  },
  relationResultContainer: {
    alignItems: "center",
  },
  relationResultText: {
    fontSize: 15,
    color: colors.text,
    fontStyle: "italic",
    fontWeight: "500",
    textAlign: "center",
  },
  evaluationMediaContainer: {
    alignItems: "center",
  },
  evaluationMediaImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: colors.gray[100],
  },
  evaluationMediaText: {
    fontSize: 10,
    color: colors.gray[600],
    marginTop: 2,
    textAlign: "center",
  },
  evaluationMediaPreview: {
    alignItems: "center",
    marginTop: 8,
  },
  evaluationMediaPreviewImageContainer: {
    position: "relative",
    alignSelf: "center",
  },
  evaluationMediaPreviewImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  editMediaButton: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  removeEvaluationMediaButton: {
    position: "absolute",
    top: -6,
    left: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.error,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  addMediaButton: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  scoreResultContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noFieldsResultContainer: {
    padding: 20,
    alignItems: "center",
    backgroundColor: colors.gray[50],
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray[200],
    borderStyle: "dashed",
  },
  noFieldsResultText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontStyle: "italic",
    fontWeight: "500",
  },
  // Styles for evaluation summary in note display
  noteContentContainer: {
    marginTop: 8,
  },
  evaluationSummary: {
    marginTop: 12,
    padding: 12,
    backgroundColor: colors.gray[50],
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  evaluationSummaryTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.primary,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  evaluationSummaryItem: {
    marginBottom: 8,
  },
  evaluationSummaryCriterion: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 4,
  },
  evaluationSummaryField: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 8,
    marginBottom: 2,
  },
  evaluationSummaryFieldName: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "500",
    flex: 1,
  },
  evaluationSummaryFieldValue: {
    fontSize: 12,
    color: colors.text,
    fontWeight: "600",
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
});
