import { colors } from "@/src/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
  },

  headerSubtitle: {
    fontSize: 14,
    color: colors.white,
    fontWeight: "500",
  },
  headerButton: {
    padding: 5,
  },
  backButton: {
    marginRight: 15,
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  chatHeaderInfo: {
    flex: 1,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
    marginLeft: 12,
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    marginTop: -10,
    margin: 15,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(102, 126, 234, 0.1)",
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  clearButton: {
    marginLeft: 8,
    padding: 4,
  },
  groupsList: {
    flex: 1,
  },
  groupItem: {
    backgroundColor: "#fff",
    marginHorizontal: 15,
    marginVertical: 6,
    borderRadius: 16,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(102, 126, 234, 0.1)",
  },
  groupItemContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
  },
  groupIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
    shadowColor: "#667eea",
    borderWidth: 1,
    borderColor: "linear-gradient(135deg, #667eea 0%,rgb(22, 72, 187) 100%)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    position: "relative",
  },
  groupIconBadge: {
    position: "absolute",
    top: -2,
    right: -2,
  },
  managerIcon: {
    backgroundColor: "linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)",
  },
  groupInfo: {
    flex: 1,
  },
  groupHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  groupName: {
    fontSize: 17,
    fontWeight: "700",
    color: "#2d3748",
    flex: 1,
    marginRight: 10,
    letterSpacing: 0.3,
  },
  lastMessageTime: {
    fontSize: 12,
    color: "#718096",
    fontWeight: "500",
  },
  groupFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  lastMessage: {
    fontSize: 14,
    color: "#718096",
    flex: 1,
    marginRight: 10,
    fontWeight: "500",
  },
  groupStats: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  memberInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  memberCount: {
    fontSize: 12,
    color: "#718096",
    marginLeft: 4,
    fontWeight: "500",
  },
  messagesList: {
    flex: 1,
  },
  messagesContainer: {
    padding: 16,
    paddingBottom: 20,
  },
  messageContainer: {
    flexDirection: "row",
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  myMessageContainer: {
    justifyContent: "flex-end",
  },
  otherMessageContainer: {
    justifyContent: "flex-start",
  },
  avatarContainer: {
    marginRight: 8,
    marginTop: 20,
    alignSelf: "flex-end",
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#1e40af",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1e40af",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  avatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e2e8f0",
  },
  avatarText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  messageContent: {
    flex: 1,
    maxWidth: "80%",
  },
  senderName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#4a5568",
    marginBottom: 6,
    marginLeft: 4,
    letterSpacing: 0.3,
  },
  senderNameInBubble: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1e40af",
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  messageBubbleContainer: {
    flexDirection: "column",
  },
  messageTime: {
    alignSelf: "flex-end",
    fontSize: 10,
    color: "#94a3b8",
    marginTop: 6,
    marginRight: 8,
  },
  messageTimeLeft: {
    alignSelf: "flex-start",
    marginLeft: 8,
    marginRight: 0,
  },
  messageTimeRight: {
    alignSelf: "flex-end",
    marginRight: 8,
  },
  messageBubble: {
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  myBubble: {
    backgroundColor: "#1e40af",
    borderBottomRightRadius: 6,
    alignSelf: "flex-end",
    shadowColor: "#1e40af",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  otherBubble: {
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 6,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(30, 64, 175, 0.1)",
    shadowColor: "#1e40af",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  messageText: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
  },
  myText: {
    color: "#fff",
    fontWeight: "600",
  },
  otherText: {
    color: "#212529",
    fontWeight: "500",
  },
  timestamp: {
    fontSize: 11,
    opacity: 0.7,
    marginTop: 6,
    marginHorizontal: 8,
    fontWeight: "500",
  },
  myTimestamp: {
    color: "#718096",
    textAlign: "right",
  },
  otherTimestamp: {
    color: "#718096",
    textAlign: "left",
  },
  inputContainer: {
    flexDirection: "column",
    padding: 16,
    paddingBottom: 20,
    // backgroundColor: "#ffffff",
    borderTopWidth: 0,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: "#ffffff",
    borderRadius: 32,
    paddingHorizontal: 6,
    paddingVertical: 6,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 1.5,
  },
  attachButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(102, 126, 234, 0.06)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 0,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  mediaPreviewContainer: {
    marginBottom: 16,
    maxHeight: 80,
    backgroundColor: "#f8fafc",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  mediaPreviewItem: {
    position: "relative",
    marginRight: 8,
  },
  mediaPreviewImage: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: "#f0f0f0",
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  removeMediaButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#fff",
    borderRadius: 14,
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  textInput: {
    flex: 1,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginRight: 12,
    maxHeight: 120,
    minHeight: 52,
    fontSize: 16,
    backgroundColor: "#ffffff",
    fontWeight: "500",
    color: "#1a202c",
  },
  sendButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  sendButtonDisabled: {
    backgroundColor: "#f1f5f9",
    shadowOpacity: 0,
    elevation: 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#718096",
    textAlign: "center",
    fontWeight: "500",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  errorText: {
    marginTop: 16,
    fontSize: 16,
    color: "#718096",
    textAlign: "center",
    marginBottom: 24,
    fontWeight: "500",
  },
  retryButton: {
    backgroundColor: "#1e40af",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: "#1e40af",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 64,
    minHeight: 200,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    color: "#999",
    textAlign: "center",
  },
  emptySubtext: {
    marginTop: 8,
    fontSize: 14,
    color: "#ccc",
    textAlign: "center",
  },
  mediaContainer: {
    marginTop: 8,
    marginBottom: 4,
  },
  imageContainer: {
    marginBottom: 8,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#f5f5f5",
  },
  messageImage: {
    borderRadius: 8,
    backgroundColor: "#fff",
  },
  imageViewerContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  imageViewerHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  imageViewerCloseButton: {
    alignSelf: "flex-end",
    padding: 10,
    borderRadius: 25,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  imageViewerContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  fullScreenImage: {
    width: "100%",
    height: "100%",
  },
  imageViewerFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: "center",
  },
  imageViewerInfo: {
    color: "#fff",
    fontSize: 14,
    opacity: 0.8,
    textAlign: "center",
  },
  dateSeparatorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
    marginHorizontal: 20,
  },
  dateSeparatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(102, 126, 234, 0.2)",
  },
  dateSeparatorText: {
    marginHorizontal: 16,
    fontSize: 12,
    fontWeight: "700",
    color: "#1e40af",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    letterSpacing: 0.5,
    shadowColor: "#1e40af",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  typingIndicator: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: "flex-start",
  },
  typingBubble: {
    backgroundColor: "#f0f0f0",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "70%",
  },
  typingText: {
    fontSize: 14,
    color: "#666",
    marginRight: 8,
  },
  typingDots: {
    flexDirection: "row",
    alignItems: "center",
  },
  typingDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#999",
    marginHorizontal: 1,
  },
  typingDot1: {
    opacity: 1,
  },
  typingDot2: {
    opacity: 0.7,
  },
  typingDot3: {
    opacity: 0.4,
  },
  typingContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  scrollToBottomButtonContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  scrollToBottomButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
});
