import { StyleSheet } from "react-native";
import { colors } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: colors.primary,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    zIndex: 0,
    marginBottom: 0,
    overflow: "hidden",
  },
  contentContainer: {
    flex: 1,
    backgroundColor: colors.mainBackground,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -28,
    paddingTop: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 5,
    flexGrow: 1,
    minHeight: "100%",
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 16,
    paddingTop: 20,
  },
  navButton: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.16)",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  weekInfo: {
    alignItems: "center",
    maxWidth: "77%",
    width: "100%",
  },
  monthYear: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: -0.4,
    lineHeight: 28,
  },
  weekRange: {
    fontSize: 15,
    color: colors.white,
    opacity: 0.85,
    marginTop: 4,
    fontWeight: "500",
    letterSpacing: 0.1,
  },
  arrowToggle: {
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  toggleRow: {
    display: "none",
  },
  segmentWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    padding: 3,
    marginVertical: 10,
    marginHorizontal: 48,
    backgroundColor: "transparent",
    borderRadius: 14,
    position: "relative",
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  segmentIndicator: {
    position: "absolute",
    left: 0,
    top: 3,
    height: 32,
    backgroundColor: colors.white,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  segmentItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
  },
  segmentText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 13,
    letterSpacing: 0.1,
  },
  segmentTextActive: {
    color: colors.white,
    fontWeight: "700",
  },
  weekStripContainer: {
    flexDirection: "row",
    backgroundColor: "transparent",
    paddingVertical: 8,
    paddingHorizontal: 20,
    paddingTop: 8,
    gap: 6,
    marginHorizontal: 0,
    marginTop: 0,
  },
  weekDayItem: { flex: 1, alignItems: "center" },
  weekDayPill: {
    width: 42,
    height: 52,
    borderRadius: 14,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 2,
  },
  weekDayPillSelected: {
    backgroundColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  weekDayName: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.white,
    opacity: 0.85,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  weekDayNameSelected: {
    color: colors.primary,
    opacity: 1,
    fontWeight: "700",
  },
  weekDayNum: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.white,
    marginTop: 4,
    letterSpacing: -0.3,
  },
  weekDayNumSelected: { color: colors.primary },
  monthNamesRow: {
    flexDirection: "row",
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 8,
    borderBottomWidth: 0,
  },
  monthNameItem: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
    color: colors.white,
    opacity: 0.85,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  monthGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingBottom: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  monthCell: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: `${100 / 7}%`,
    width: `${100 / 7}%`,
    paddingVertical: 4,
    paddingHorizontal: 0,
    alignItems: "center",
    marginVertical: 0,
    minHeight: 60,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  monthDayContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingHorizontal: 2,
    minHeight: 36,
  },
  monthDayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  monthDayText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.white,
    letterSpacing: -0.2,
  },
  selectedDayHeader: {
    backgroundColor: "rgba(255,255,255,0.9)",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  todayDayHeader: {
    backgroundColor: "rgba(255,255,255,0.24)",
    borderWidth: 0,
  },
  selectedDayName: {
    color: colors.primary,
    fontWeight: "700",
  },
  todayDayName: {
    color: colors.white,
    fontWeight: "700",
  },
  monthEventPill: {
    backgroundColor: colors.white,
    borderRadius: 8,
    paddingVertical: 2,
    marginTop: 3,
  },
  monthEventText: {
    fontSize: 9,
    textAlign: "center",
    color: colors.primary,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  moreLabel: {
    marginTop: 4,
    fontSize: 9,
    color: colors.white,
    fontWeight: "600",
    opacity: 0.7,
  },
  teachingDot: {
    position: "absolute",
    bottom: -12,
    left: "52%",
    marginLeft: -3,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.white,
  },
  loadingContainer: {
    position: "absolute",
    top: "20%",
    left: "50%",
    transform: [{ translateX: -50 }, { translateY: -50 }],
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.text,
    opacity: 0.7,
  },
  daySection: {
    marginBottom: 24,
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 0,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
    overflow: "hidden",
  },
  daySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0,
    backgroundColor: "#fafbfc",
  },
  dayHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 16 },
  dayTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.3,
  },
  daySubtitle: {
    fontSize: 13,
    color: colors.text,
    opacity: 0.6,
    marginTop: 3,
    fontWeight: "500",
  },
  dateBubble: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 119, 190, 0.06)",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  dateBubbleToday: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  dateBubbleDay: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: -0.4,
  },
  dateBubbleDayToday: { color: colors.white },
  todayChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.primary,
    borderRadius: 20,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  todayChipText: {
    fontSize: 12,
    color: colors.white,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  compactEmptyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  compactEmptyText: {
    fontSize: 15,
    color: colors.text,
    opacity: 0.6,
    fontWeight: "500",
  },
  emptyDayContainer: {
    borderRadius: 16,
    padding: 24,
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 80,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  weekSelectedHeader: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  weekSelectedTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  emptyDayText: {
    fontSize: 16,
    color: colors.gray[500],
    textAlign: "center",
    fontStyle: "italic",
    fontWeight: "500",
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.white,
    borderRadius: 16,
    marginBottom: 8,
    marginHorizontal: 14,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.04)",
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },
  timePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 119, 190, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18,
    marginRight: 10,
    gap: 4,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  timePillText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: 0.1,
  },
  sessionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 4,
    lineHeight: 20,
    letterSpacing: -0.2,
  },
  sessionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
    flexWrap: "wrap",
  },
  sessionMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 119, 190, 0.06)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  sessionMetaText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  // Course-card like styles (to match ScheduleScreen)
  courseHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  courseIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  courseInfo: { flex: 1 },
  sessionCourseName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 4,
  },
  sessionCourseInstructor: {
    fontSize: 14,
    color: colors.grayc,
  },
  courseDate: {
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  courseDateText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.primary,
  },
  courseDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  courseDetailItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  courseDetailText: {
    fontSize: 12,
    color: colors.grayc,
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    justifyContent: "flex-end",
    paddingBottom: 0,
  },
  modalContentn: {
    flex: 1,
    backgroundColor: colors.mainBackground,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "65%",
    marginBottom: 0,
  },
  modalContent: {
    backgroundColor: colors.mainBackground,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "95%",
    height: "90%",
    marginBottom: 0,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    overflow: "hidden",
  },
  modalSwipeHandle: {
    position: "absolute",
    top: 8,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 0,
    backgroundColor: "transparent",
    zIndex: 10,
  },
  modalSwipeHandleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.gray[400],
    opacity: 0.5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.04)",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.4,
  },
  closeButton: {
    fontSize: 16,
    position: "absolute",
    right: 20,
    top: 20,
    color: colors.white,
    opacity: 0.5,
    fontWeight: "300",
  },
  // Upcoming courses styles
  upcomingCoursesSection: {
    backgroundColor: colors.mainBackground,
    marginTop: 16,
    marginHorizontal: 0,
    borderRadius: 0,
    padding: 24,
    paddingTop: -8,
    shadowColor: colors.black,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.4,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "rgba(0, 119, 190, 0.06)",
    borderRadius: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: 0.1,
  },
  courseCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    position: "relative",
    overflow: "visible",
  },
  attendanceBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  courseName: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.3,
  },
  accordionContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(0, 62, 159, 0.08)",
    overflow: "hidden",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    paddingVertical: 18,
    backgroundColor: colors.white,
    borderBottomWidth: 0,
  },
  accordionHeaderExpanded: {
    backgroundColor: "rgba(0, 62, 159, 0.02)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 62, 159, 0.08)",
  },
  accordionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 12,
  },
  accordionSlotBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  accordionSlotNumber: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: 0.2,
  },
  accordionHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  accordionIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 62, 159, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 62, 159, 0.15)",
  },
  accordionInfo: {
    flex: 1,
  },
  accordionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 6,
    letterSpacing: -0.2,
  },
  accordionTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  accordionTime: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.gray[600],
    letterSpacing: 0.2,
  },
  accordionTimeSeparator: {
    fontSize: 13,
    color: colors.gray[400],
    marginHorizontal: 2,
  },
  accordionSlotInfo: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.primary,
    maxWidth: 150,
  },
  accordionChevron: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0, 62, 159, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 62, 159, 0.12)",
  },
  accordionContent: {
    backgroundColor: colors.mainBackground,
    overflow: "hidden",
  },
  // Filter info styles
  filterInfoContainer: {
    marginTop: 6,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    alignSelf: "center",
  },
  filterInfoWrapper: {
    position: "relative",
    width: "100%",
    alignItems: "center",
  },
  filterInfoText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.white,
    opacity: 0.8,
    textAlign: "center",
  },
  filterInfoBadge: {
    position: "absolute",
    top: -12,
    right: 0,
    backgroundColor: colors.white,
    borderRadius: 6,
    paddingHorizontal: 3,
    paddingVertical: 1,
    minWidth: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  filterInfoBadgeText: {
    fontSize: 8,
    fontWeight: "700",
    color: colors.primary,
    lineHeight: 10,
  },
  // Filter modal styles
  filterModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  filterModalContent: {
    backgroundColor: colors.white,
    borderRadius: 28,
    width: "100%",
    maxWidth: 500,
    maxHeight: "85%",
    minHeight: 600,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 12,
    overflow: "hidden",
    flexDirection: "column",
  },
  filterModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  filterModalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.5,
  },
  filterModalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray[100],
    alignItems: "center",
    justifyContent: "center",
  },
  filterModalScroll: {
    backgroundColor: colors.mainBackground,
    flex: 1,
    maxHeight: "100%",
  },
  filterModalScrollContent: {
    padding: 24,
    paddingBottom: 32,
    flexGrow: 1,
    backgroundColor: colors.mainBackground,
  },
  filterSection: {
    marginBottom: 28,
  },
  filterSectionTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.gray[600],
    marginBottom: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dateRangeContainer: {
    gap: 12,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    borderWidth: 2,
    borderColor: colors.gray[200],
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    gap: 14,
    justifyContent: "space-between",
    minHeight: 72,
  },
  datePickerButtonContent: {
    flex: 1,
  },
  datePickerLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.gray[500],
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  datePickerValue: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.2,
  },
  classFilterContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  classFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 2,
    borderColor: colors.gray[200],
    gap: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  classFilterChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  classFilterChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    letterSpacing: -0.1,
  },
  classFilterChipTextSelected: {
    color: colors.white,
    fontWeight: "700",
  },
  classFilterCheckmark: {
    marginLeft: -2,
  },
  noClassesContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
    backgroundColor: colors.gray[50],
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.gray[100],
    borderStyle: "dashed",
  },
  noClassesText: {
    fontSize: 14,
    color: colors.gray[500],
    fontWeight: "500",
    textAlign: "center",
    marginTop: 12,
  },
  clearFilterButton: {
    marginTop: 14,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.gray[50],
  },
  clearFilterText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.primary,
  },
  filterModalFooter: {
    flexDirection: "row",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.gray[100],
    gap: 12,
    backgroundColor: colors.mainBackground,
  },
  resetFilterButton: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.gray[400],
    flexDirection: "row",
    gap: 6,
  },
  resetFilterText: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.2,
  },
  applyFilterButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    flexDirection: "row",
    gap: 6,
  },
  applyFilterText: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: -0.2,
  },
  // Date Picker inline styles
  datePickerInlineContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  datePickerInlineHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
    backgroundColor: colors.white,
  },
  datePickerBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray[100],
    alignItems: "center",
    justifyContent: "center",
  },
  datePickerInlineTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    flex: 1,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  datePickerContent: {
    flexDirection: "row",
    paddingVertical: 20,
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  datePickerColumn: {
    flex: 1,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: colors.gray[100],
  },
  datePickerColumnLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.gray[600],
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  datePickerScroll: {
    flex: 1,
    width: "100%",
  },
  datePickerOption: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginHorizontal: 6,
    marginVertical: 2,
    minWidth: 50,
  },
  datePickerOptionSelected: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  datePickerOptionText: {
    fontSize: 15,
    color: colors.text,
    fontWeight: "600",
  },
  datePickerOptionTextSelected: {
    color: colors.white,
    fontWeight: "700",
  },
  datePickerInlineFooter: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.gray[100],
    backgroundColor: colors.white,
  },
  datePickerConfirmInlineButton: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    flexDirection: "row",
    gap: 8,
  },
  datePickerConfirmInlineText: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: -0.2,
  },
});
