import { StyleSheet } from "react-native";
import { colors } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  navButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
  },
  weekInfo: { alignItems: "center" },
  monthYear: { fontSize: 18, fontWeight: "bold", color: colors.text },
  weekRange: { fontSize: 14, color: colors.text, opacity: 0.7, marginTop: 2 },
  toggleRow: {
    display: "none",
  },
  segmentWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    padding: 3,
    marginVertical: 10,
    marginHorizontal: 16,
    backgroundColor: "#f4f7fb",
    borderRadius: 12,
    position: "relative",
  },
  segmentIndicator: {
    position: "absolute",
    left: 0,
    top: 3,
    height: 36,
    backgroundColor: colors.white,
    borderRadius: 9,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
  },
  segmentText: {
    color: colors.text,
    fontWeight: "700",
    fontSize: 13,
  },
  segmentTextActive: { color: colors.primary },
  weekStripContainer: {
    flexDirection: "row",
    backgroundColor: colors.white,
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  weekDayItem: { flex: 1, alignItems: "center" },
  weekDayPill: {
    width: 56,
    height: 72,
    borderRadius: 14,
    backgroundColor: "#f2f6f9",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
  },
  weekDayPillSelected: { backgroundColor: "rgba(0,119,190,0.12)" },
  weekDayName: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.text,
    opacity: 0.7,
  },
  weekDayNameSelected: { color: colors.primary, opacity: 1 },
  weekDayNum: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginTop: 4,
  },
  weekDayNumSelected: { color: colors.primary },
  monthNamesRow: {
    flexDirection: "row",
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingTop: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  monthNameItem: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
    opacity: 0.7,
    marginBottom: 8,
  },
  monthGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingBottom: 12,
    borderLeftWidth: 1,
    borderTopWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
  },
  monthCell: {
    width: `${100 / 7}%`,
    paddingVertical: 6,
    paddingHorizontal: 2,
    alignItems: "stretch",
    marginVertical: 1,
    minHeight: 60,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
  },
  monthDayContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  monthDayCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  monthDayText: { fontSize: 11, fontWeight: "700", color: colors.text },
  selectedDayHeader: {
    backgroundColor: colors.primary,
    borderRadius: 14,
  },
  todayDayHeader: {
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    borderRadius: 14,
  },
  selectedDayName: { color: colors.white },
  todayDayName: { color: colors.primary },
  monthEventPill: {
    backgroundColor: "#eef6fb",
    borderRadius: 3,
    paddingHorizontal: 3,
    paddingVertical: 1,
    marginTop: 1,
  },
  monthEventText: { fontSize: 9, color: colors.primary, fontWeight: "700" },
  moreLabel: {
    marginTop: 4,
    fontSize: 10,
    color: colors.grayc,
    fontWeight: "700",
  },
  teachingIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginLeft: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 50,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.text,
    opacity: 0.7,
  },
  daySection: {
    marginBottom: 18,
    backgroundColor: colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    elevation: 2,
    overflow: "hidden",
  },
  daySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
    backgroundColor: "#fdfefe",
  },
  dayHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  dayTitle: { fontSize: 16, fontWeight: "700", color: colors.text },
  daySubtitle: { fontSize: 12, color: colors.text, opacity: 0.6, marginTop: 2 },
  dateBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 119, 190, 0.1)",
  },
  dateBubbleToday: { backgroundColor: colors.primary },
  dateBubbleDay: { fontSize: 16, fontWeight: "800", color: colors.primary },
  dateBubbleDayToday: { color: colors.white },
  todayChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.primary,
    borderRadius: 999,
  },
  todayChipText: {
    fontSize: 12,
    color: colors.white,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  compactEmptyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  compactEmptyText: { fontSize: 13, color: colors.text, opacity: 0.6 },
  emptyDayContainer: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 60,
  },
  emptyDayText: {
    fontSize: 14,
    color: colors.gray[500],
    textAlign: "center",
    fontStyle: "italic",
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
    borderRadius: 12,
    marginBottom: 8,
    marginHorizontal: 16,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  timePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 12,
    gap: 4,
  },
  timePillText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.white,
  },
  sessionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 4,
    lineHeight: 20,
  },
  sessionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
    flexWrap: "wrap",
  },
  sessionMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  sessionMetaText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
    paddingBottom: 0,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "78%",
    marginBottom: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#333" },
  closeButton: { fontSize: 24, color: "#666" },
  // Upcoming courses styles
  upcomingCoursesSection: {
    backgroundColor: colors.white,
    marginTop: 16,
    marginHorizontal: 0,
    borderRadius: 0,
    padding: 16,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(0, 119, 190, 0.1)",
    borderRadius: 16,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary,
  },
  courseCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 0,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  courseName: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.text,
  },
});
